#!/usr/bin/env bash
#Install nginx web server configures it on a remote server
sudo apt-get -y  update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
# OR
#echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
