#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server
sudo apt-get -y update
sudo apt-get install -y haproxy
#enable the managment via the innit script
echo "ENABLED=1" >> /etc/default/haproxy

#rename te existing file before creating new config
mv /etc/haproxy/haproxy.cfg{,.original}
#create haproxy.cfg file
touch /etc/haproxy/haproxy.cfg
printf % "global
	log 127.0.0.1 local notice
	maxconn 2000
	user haproxy
	group haproxy

defaults
	log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http
backend web-backend
	timeout connect 3000
	timeout server 30000
	balance roundrobin
	option fowardfor
	server 269747-web-01 100.25.104.17:80 check
	server 269747-web-02 35.174.205.159:80 check
frontend proxynode
	timeout client 30000
	bind *:80
	mode http
	default_backend web-backend
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
